language: ruby
sudo: false
before_install: gem install bundler
bundler_args: --without development
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.4
